package com.javalangPackage.variousMethods;

public class HashCode {

    /*
     *
     * for every object a unique number generated by JVM which is nothing but hashcode of that object
     * hashcode wont represent address of the object, JVM will use hashcode while saving objects into 
     * hashing related collections like HashMap, HashSet, Hashtable etc
     * hashCode() method is used to get the hashcode of an object
     * hashcode is a unique integer number which is used to identify an object
     * hashcode is used in hashing based collections like HashMap, HashSet, Hashtable etc
     * Whenever we are trying to print object reference internally toString() wil be called
     * If our class doesnt contain toString() then Object class toStirng() will be executed
     * In all wrapper classes , all collection classes string class stringBuffer and stringBuilder 
     * classes toString() is overridden for meaningful string representation, Hence it is highlt 
     * recommended to override toString() in our class also
     * We can override the hashCode() method to get meaningful hashcode of an object
     * if we are giving chance to Object class totring() it will internally calls hashcode()
     * If we are overridng the toString() then our toString() may not call hashcode() method
     * 
    
    */

    public static void main(String[] args)
    {
        HashCode h = new HashCode();
        System.out.println(h.hashCode());
        System.out.println(h);
    }
    
}
